### ISSUE TITLE
Error when trying to run the app --> Error:Internal error: (java.lang.ClassNotFoundException) 

### ISSUE THREAD

**Issue by jorjoel777** [mapbox/store-locator-android#27]
Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:86)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:214)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:73)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:74)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexBuilder.buildStarted(JavaBackwardReferenceIndexBuilder.java:40)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:358)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:229)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by langsmith** [comment]
@jorjoel777 , is this preventing you from running the app? Leading to a crash?

**Comment by jorjoel777** [comment]
Correct. It crashes and I cannot view anything on the mobile emulator.

**Comment by langsmith** [comment]
Is your mapbox access token correct? https://account.mapbox.com/access-tokens/

Have you changed other code? Is there any other crash information? Based on what you posted, I don't see anything related to Mapbox nor anything that would kill the app. Is there a `FATAL` message in the logcat when the crash happens?

**Comment by keshavwy** [comment]
@langsmith - I'm also facing the same issue. Here are the logs

Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:86)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:214)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:73)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:74)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexBuilder.buildStarted(JavaBackwardReferenceIndexBuilder.java:40)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:358)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:229)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


It's not crashing the app, but fail to launch the app. Can you guide on this?

**Comment by jorjoel777** [comment]
I found out that it was related to using multiple displays as I do at the
office. When I ran it on my laptop from home the mobile emulator did work
so some of the errors disappeared, I think the rest of errors are due to
config of the editor you are using.

**Comment by langsmith** [comment]
@jorjoel777 , thanks for the update. 

@keshavwy , have you made any adjustments to the project on your machine? Your Android Studio is up-to-date? Fresh install of the project on your device? What's the FATAL error in your logcat when the the app installs but doesn't actually launch?

**Comment by whocen** [comment]
Hello guys I am facing this very problem on my flutter app has any one fixed this yet?

**Comment by langsmith** [comment]
@whocen ,  this app wasn't made with Flutter in mind. A non-Mapbox Flutter project is being worked on at https://github.com/tobrun/flutter-mapbox-gl

Despite all of that, have you made any adjustments to the project on your machine? Your Android Studio is up-to-date? Fresh install of the project on your device? What's the FATAL error in your logcat when the the app installs but doesn't actually launch?

**Comment by iatomic** [comment]
The moment Android Studio moved to IntelliJ it is a total DISASTER.
I just imported a project from Eclipse ADT...tried to compile...

java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index


what a LOAD OF JUNK this tool is.
Anyone has an idea what is going on?

**Comment by purlintan** [comment]
try to change the java compiler, use Eclipse.

**Comment by AbhiAgarwal192** [comment]
If you are using android studio, what are the android sdk versions available?

**Comment by langsmith** [comment]
Closing as this has become stale and/or because the conversation has deviated from @jorjoel777's latest crash comment in May 2019. Haven't heard back after https://github.com/mapbox/store-locator-android/issues/27#issuecomment-492691715.

**Comment by sppanday** [comment]
3.5

**Comment by kumarrahul-rkv** [comment]
I have same issue in the android studio using Flutter.

Resolved issue by doing the following steps:
1. Created a blank app
2. imported my flutter script by configuring "android gradle" setting from an external source.

My application ran successfully

**Comment by AnPvn** [comment]
I am a begginer on Android Development. I got an idea to decompile an APK and change the value of one variable on the code . . .. . Ok, but when I try to recompile to APK, i got the same error message. Please help me. I do not know what can i do to solve it.

**Comment by GoGoal92** [comment]
File-->Settings-->Build, Execution, Deployment---> Java Compiler --> use Compiler as ' Eclipse' instead of javac

**Comment by robauer22** [comment]
Tried GoGoal92 suggestion - it didn't work

**Comment by manglide** [comment]
> File-->Settings-->Build, Execution, Deployment---> Java Compiler --> use Compiler as ' Eclipse' instead of javac

Worked for me

**Comment by piterbajk** [comment]
@GoGoal92 You are my hero, finally managed to run ANT+ Plugin Sampler!

**Comment by Lido233** [comment]
> > File-->Settings-->Build, Execution, Deployment---> Java Compiler --> use Compiler as ' Eclipse' instead of javac
> 
> Worked for me

I met the same problem.But under my compiler there is not java compiler.Please help i'm stuck here for too long.

**Comment by osed23** [comment]
> File-->Settings-->Build, Execution, Deployment---> Java Compiler --> use Compiler as ' Eclipse' instead of javac

it worked for me

**Comment by DoumSof99** [comment]
_File-->Settings-->Build, Execution, Deployment---> Java Compiler --> use Compiler as ' Eclipse' instead of javac_
it worked perfectly for me too
