### ISSUE TITLE
Is there anyway I can get the dataset from firebase?

### ISSUE THREAD

**Issue by CodeBlooded-io** [mapbox/store-locator-android#37]
I tried by getting a datasnapshot object of the data and then converting it into json and then passing it in 
`featureCollection = FeatureCollection.fromJson(json);`
But it seems that app crashes by the time it receives data from firebase.

I am able to see the retrieved firebase data about 3 seconds later in the log when I get the featureCollection data from local json.

**Comment by langsmith** [comment]
Hey @CodeBlooded-io , thanks for your interest in this project. 

What's the crash message in your logcat when the crash happens? Search for the word `FATAL`. 

Maybe your JSON isn't correctly structured in the GeoJSON/`FeatureCollection`? Paste your `FeatureCollection` into the righthand side window of http://geojson.io to validate it. There's also https://geojsonlint.com.

**Comment by CodeBlooded-io** [comment]
I had no luck validating both featureCollection(s), the firebase and the local geoJson file ones but they are the same when I compared and have been giving result.

This is the message I am getting in logcat when I try to use firebase - 

2020-07-14 11:08:33.235 28812-28812/com.mapbox.storefinder E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.geojson.FeatureCollection.features()' on a null object reference
        at com.mapbox.storelocator.activity.MapActivity$1$1.onStyleLoaded(MapActivity.java:203)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-14 11:08:33.597 28812-28812/com.mapbox.storefinder E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
2020-07-14 11:08:33.604 28812-28812/com.mapbox.storefinder A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28812 (box.storefinder), pid 28812 (box.storefinder)


Now I tried an experiment, initially I let the featureCollection get the data from local geoJson and I also kept the firebase one, like below - 

`private void getFeatureCollectionFromJson() throws IOException {
    final String[] json = new String[1];
    try {
      // Use fromJson() method to convert the GeoJSON file into a usable FeatureCollection object
      rootRef.addValueEventListener(new ValueEventListener() {
        @Override
        public void onDataChange(DataSnapshot dataSnapshot) {
          Object object = dataSnapshot.getValue(Object.class);
          json[0] = new Gson().toJson(object);
          Log.d("json","jsonobject: " + object);
          Log.d("json","json: " + json[0]);

          featureCollection = FeatureCollection.fromJson(json[0]);
          Log.d("json","feature1: " + featureCollection);
        }

        @Override
        public void onCancelled(@NonNull DatabaseError databaseError) {

        }
      });

      featureCollection = FeatureCollection.fromJson(loadGeoJsonFromAsset("list_of_locations.geojson"));
      Log.d("json","feature: " + featureCollection);
      //Log.d("json","json: " + featureCollection);
    } catch (Exception exception) {
      Log.e("MapActivity", "getFeatureCollectionFromJson: " + exception);
    }
  }`

So when I launch the app for the first time it loads from the local geoJson file. Then I hit back, reach the themepicker activity and then go to the MapActivity again. This time it loads from the firebase. I believe it is the time problem. It takes time to load firebase data that is why the app is crashing.

**Comment by CodeBlooded-io** [comment]
Hey! I solved the problem by caching firebase data locally. Thank you :)
